### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by sero583**
Was bpred so thought to help out a little bit

### CODE REVIEW

**Comment by sero583** [comment]
Sorry for the messy formatting

**Comment by corytortoise** [comment]
Everything looks great except for the last commit. Each arena data will have 2 arrays and a "level" stored, so the original is incorrect, but just needs a deletion.(I think)

Example:

arenas:
  0:
    - x1
    - y1
    - z1
    - yaw1
    - pitch1
  1:
    - x2
    - y2
    - z2
    - yaw2
    - pitch2
  level: world

**Comment by sero583** [comment]
@corytortoise Look you made a function which just includes one array thats why you need to fix it but I'ma change it now

**Comment by sero583** [comment]
It has only one $data argument if youre getting what I mean

**Comment by sero583** [comment]
What is in the Sign included?
Time? Or just if it started and player count, if so then remove SignUpdateTask and update the text just once

**Comment by corytortoise** [comment]
My plans were to at least have the sign contain a count of all arenas, and possibly a player/active arena count.

**Comment by sero583** [comment]
@corytortoise Then a extra task isn't needed and just eats important resources, you can handle that per Events

**Comment by corytortoise** [comment]
Good point, thanks for the advice.

**Comment by sero583** [comment]
@corytortoise Also if you'd like to add 2vs2 you need to use
``EntityDamageByEntityEvent`` and and something kind of like a getter like ``getType();`` which returns a String ``1vs1`` or ``2vs`` or Integers ``1`` would stay for 1vs1 and ``2`` for 2vs2 and add in the construct another argument for 1vs1 or 2vs2 and handle everything later like that. For the events just dont fill the other arguments and add a getter for which session it was and if it was the winner team add ``getWinnerTeamData();`` which would return maybe a array like that ``0 => 1`` (stays for team one) and to the other add ``1 => Player $winner1`` and ``Player $winner2``

**Comment by sero583** [comment]
Or edit it like that that both extends something which is actually ``Arena.php`` for example and the real classes would be ``OneVSOneArena.php`` and ``TwoVSTwoArena.php``, the rest explains itself I guess

**Comment by corytortoise** [comment]
Yea, I have been focused on basic 1vs1 right now, but I should just implement 2vs2 so I won't need to rewrite everything later. I'm busy right now, but I'll start working on this again in a few days.

**Pull request merged**
